---
sidebar: sidebar
permalink: fixed-issues.html
keywords: fixed issues, release notes, fixes, gfc, global file cache
summary: See what issues have been fixed in Global File Cache.
---

= Fixed issues in Global File Cache
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
See what issues have been fixed in Global File Cache.

== 23 June 2022 (version 1.3.1)

* Upon upgrade, the correct version of Microsoft re-distributable is not installed correctly and as a result Tum does not start. The GFC installer has been fixed to install the correct version re-distributable.
* The GFC License Manager Service (LMS) now updates the configuration information, instead of overwriting it.
* The Configuration UI now binds to the correct System.net.http dll during the upgrade process.

== 19 May 2022 (version 1.3.0)

* The Configuration UI page for Edge Sync functionality is updated.
* Fixed an issue when adding pre-population jobs for multiple Edges at the same time via PowerShell cmdlets.
* Fixed a display issue in LMS Web UI that displays the NetApp subscription.
* The LMS configuration PowerShell script now uses TLS 1.2.
* Fixed an issue in TappN (pre-population service) and enabled it to continue executing the job, despite transient disconnections or Tum restarts.
* The TappN pre-population service is updated to skip fetching files if free cache space falls below the lower threshold value.
* Fixed an issue in the License Manager Server Service (LMS) while writing a trace log.
* The Logging infrastructure for Tum is updated to be more scalable with high performance.

== 17 December 2021 (version 1.2.0)

* The Configuration UI (Optimus) is enhanced to validate the date field entries while adding pre-population jobs.
* Pre-population is enhanced to monitor cache utilization and will skip populating if cache usage reaches close to cache cleaner parameters.
* Removed the hard dependency of the License Management Server (LMS) Service running locally with Policy configuration.
* The GFC Kernel driver is enhanced to avoid a crash in the SMB Server service in Windows Server 2016/2019.
* Fixed an exception in the LMS Service.
* Service Start types for the License Manager Server Service (LMS), License Manager Client Service (LMC), and Pre-population Service (TappN) are changed from 'Automatic Delayed' to 'Automatic'.

== 9 June 2021 (version 1.1.0)

* The Configuration UI now displays the Edge hostname correctly in the Edit Pre-population page.
* An issue in parsing the json response from the NetApp License subscription server during license registration is fixed.
* Pre-population (TappN) logs are enhanced to log the file transfer status of all the files.

== 7 April 2021 (version 1.0.4)

* A QoS issue has been fixed where QoS parameters were applied to _all_ users instead of just the user who surpassed the limits.
* NSS credentials are now validated before being applied to the licensing system.
* Race conditions between the GFC software and certain antivirus software have been fixed.
* A crash no longer occurs when a locking hierarchy is violated during drop lease operations.

== 21 March 2021 (version 1.0.3)

* The NetApp license registration and GFC subscription-based registration is only allowed by the cloud-based License Management Server (LMS). The on-premises LMS should use legacy licensing.
* The Configuration UI now adds jobs in pre-population when the License Manager Client Service (LMC) uses hostnames instead of IP address for the LMS during configuration.
