---
sidebar: sidebar
permalink: fixed-issues.html
keywords: fixed issues, release notes, fixes, gfc, global file cache
summary: See what issues have been fixed in Global File Cache.
---

= Fixed issues in Global File Cache
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
See what issues have been fixed in Global File Cache.

== 25 July 2022 (version 2.0)

* Optimus is enhanced by adding boundary limits to date/time parameters for pre-population job addition configuration.
* Optimus PSM now shows the correct CPU details in system pre-requisition details.
* Fixed an exception in the UI during Edge Sync configuration between entering coordinator details and clicking the Refresh button.
* Enhanced the Optimus UI to enable/disable the Edge Sync feature on the edge.
* Fixed the date range issue in License Server Manager for Zuora License Aggregator.
* Fixed the Optimus PSM to show Lease Count information.
* Fixed License Management Server's logic on configuration updater during an upgrade.

== 23 June 2022 (version 1.3.1)

* Upon upgrade, the correct version of Microsoft re-distributable is not installed correctly and as a result Tum does not start. The GFC installer has been fixed to install the correct version re-distributable.
* The GFC License Manager Service (LMS) now updates the configuration information, instead of overwriting it.
* The Configuration UI now binds to the correct System.net.http dll during the upgrade process.

== 19 May 2022 (version 1.3.0)

* The Configuration UI page for Edge Sync functionality is updated.
* Fixed an issue when adding pre-population jobs for multiple Edges at the same time via PowerShell cmdlets.
* Fixed a display issue in LMS Web UI that displays the NetApp subscription.
* The LMS configuration PowerShell script now uses TLS 1.2.
* Fixed an issue in TappN (pre-population service) and enabled it to continue executing the job, despite transient disconnections or Tum restarts.
* The TappN pre-population service is updated to skip fetching files if free cache space falls below the lower threshold value.
* Fixed an issue in the License Manager Server Service (LMS) while writing a trace log.
* The Logging infrastructure for Tum is updated to be more scalable with high performance.

== 17 December 2021 (version 1.2.0)

* The Configuration UI (Optimus) is enhanced to validate the date field entries while adding pre-population jobs.
* Pre-population is enhanced to monitor cache utilization and will skip populating if cache usage reaches close to cache cleaner parameters.
* Removed the hard dependency of the License Management Server (LMS) Service running locally with Policy configuration.
* The GFC Kernel driver is enhanced to avoid a crash in the SMB Server service in Windows Server 2016/2019.
* Fixed an exception in the LMS Service.
* Service Start types for the License Manager Server Service (LMS), License Manager Client Service (LMC), and Pre-population Service (TappN) are changed from 'Automatic Delayed' to 'Automatic'.

== 9 June 2021 (version 1.1.0)

* The Configuration UI now displays the Edge hostname correctly in the Edit Pre-population page.
* An issue in parsing the json response from the NetApp License subscription server during license registration is fixed.
* Pre-population (TappN) logs are enhanced to log the file transfer status of all the files.
