---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, gfc, global file cache
summary: Learn what's new in Global File Cache.
---

= What's new with Global File Cache
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Global File Cache.

// tag::whats-new[]
== 19 May 2022 (version 1.3.0)

Global File Cache Edge software for version 1.3.0 is available at https://docs.netapp.com/us-en/cloud-manager-file-cache/download-gfc-resources.html#download-required-resources[this page].

=== New Metadata Edge Sync feature

This "Metadata Edge Sync" feature uses the Edge Synchronization feature as its core framework. Only Metadata information is updated on all subscribed Edges and the files/folders get created on the Edge machines.

=== License Manager Service enhancements

The Global File Cache License Management Server (LMS) service is enhanced to auto detect proxy settings. This enables a seamless configuration.

== 17 December 2021 (version 1.2.0)

=== The OpenSSL module has been upgraded to version 1.1.1l.

This is the latest version and it is more secure. This module is used for secure communication between GFC Edge and GFC Core.

=== The logging infrastructure has been enhanced.

== 9 June 2021 (version 1.1.0)

=== The "Edge Synchronization" feature has been added.

This feature keeps multiple Edges at a remote office in sync and the data is always cached/warm. When a file is flushed/fetched at one Edge, then the same file on all Edges participating in Edge Sync is updated and cached. See section 8.4 in the https://repo.cloudsync.netapp.com/gfc/Netapp%20GFC%20User%20Guide%201.1.0.pdf[NetApp Global File Cache User Guide^] for details.

=== The OpenSSL module has been upgraded to version 1.1.1k.

This is the latest version and it is more secure. This module is used for secure communication between GFC Edge and GFC Core.

=== Updated License Registration Page.

The GFC License Registration Page now displays the number of licenses when activated through a NetApp subscription.
// end::whats-new[]

== 21 March 2021 (version 1.0.3)

=== Software installer updates to automatically exclude GFC process from Windows Defender.

The Global File Cache software installer now excludes all GFC processes from Windows Defender software on-demand scanning.

=== A new Policy Configuration tab has been added to the Configuration Console.

This configuration tab enables you to add pre-population jobs from the GFC Core.

=== Enhanced the software to use less memory while increasing performance and stability.
