---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, gfc, global file cache
summary: Learn what's new in Global File Cache.
---

= What's new with Global File Cache
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in Global File Cache.

// tag::whats-new[]
== 25 July 2022 (version 2.0)

This release provide the new features listed below. It also fixes the issues described in the https://docs.netapp.com/us-en/cloud-manager-file-cache/fixed-issues.html[Fixed Issues].

=== New capacity-based licensing model for Global File Cache through the Azure Marketplace

A new "Edge Cache" license has the same capabilities as the "CVO Professional" license, but it also includes support for Global File Cache. You'll see this option when deploying a new Cloud Volumes ONTAP system in Azure. You are entitled to deploy one Global File Cache Edge system for each 3 TiB of provisioned capacity on the Cloud Volumes ONTAP system. A minimum of 30 TiB should be provisioned. The GFC License Manager Service has been enhanced to provide capacity-based licensing.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing[Learn more about the Edge Cache license package.]

=== Global File Cache is now integrated with Cloud Insights

NetApp Cloud Insights (CI) gives complete visibility into your infrastructure and applications. Global File Cache is now integrated with CI to provide complete visibility of all edges and cores; monitoring processes running on the instances. Various Global File Cache metrics are pushed to CI to provide a complete overview on the CI dashboard.

https://cloud.netapp.com/cloud-insights[Learn more about Cloud Insights.]

=== License Management Server has been enhanced to operate in very restrictive environments

During license configuration, the License Management Server (LMS) should have access to the internet to collect the licensing details from NetApp/Zuora. Once the configuration is successful, the LMS can continue to work in offline mode and provide licensing capabilities despite being in restrictive environments.

=== The Edge Sync UI in Optimus has been enhanced to show the list of connected clients on a coordinator Edge

== 23 June 2022 (version 1.3.1)

Global File Cache Edge software for version 1.3.1 is available at https://docs.netapp.com/us-en/cloud-manager-file-cache/download-gfc-resources.html#download-required-resources[this page]. This release fixes the issues described in the https://docs.netapp.com/us-en/cloud-manager-file-cache/fixed-issues.html[Fixed Issues].

== 19 May 2022 (version 1.3.0)

Global File Cache Edge software for version 1.3.0 is available at https://docs.netapp.com/us-en/cloud-manager-file-cache/download-gfc-resources.html#download-required-resources[this page].

=== New Metadata Edge Sync feature

This "Metadata Edge Sync" feature uses the Edge Synchronization feature as its core framework. Only Metadata information is updated on all subscribed Edges and the files/folders get created on the Edge machines.

=== License Manager Service enhancements

The Global File Cache License Management Server (LMS) service is enhanced to auto detect proxy settings. This enables a seamless configuration.
// end::whats-new[]

== 17 December 2021 (version 1.2.0)

=== The OpenSSL module has been upgraded to version 1.1.1l

This is the latest version and it is more secure. This module is used for secure communication between GFC Edge and GFC Core.

=== The logging infrastructure has been enhanced

== 9 June 2021 (version 1.1.0)

=== The "Edge Synchronization" feature has been added

This feature keeps multiple Edges at a remote office in sync and the data is always cached/warm. When a file is flushed/fetched at one Edge, then the same file on all Edges participating in Edge Sync is updated and cached. See section 8.4 in the https://repo.cloudsync.netapp.com/gfc/Netapp%20GFC%20User%20Guide%201.1.0.pdf[NetApp Global File Cache User Guide^] for details.

=== The OpenSSL module has been upgraded to version 1.1.1k

This is the latest version and it is more secure. This module is used for secure communication between GFC Edge and GFC Core.

=== Updated License Registration Page

The GFC License Registration Page now displays the number of licenses when activated through a NetApp subscription.
